[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml[html-clean]>=6.0.0",
    "newspaper3k>=0.2.8",
    "requests>=2.32.4",
    "schedule>=1.2.2",
]
