services:
  - type: web
    name: news-scraper-dashboard
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: news-scraper-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: news-scraper-db
    databaseName: news_scraper
    user: news_scraper_user
    plan: starter