
services:
  - type: web
    name: pulseebackend
    env: python
    buildCommand: |
      # Install Node.js dependencies and build frontend
      npm install
      npm run build
      
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Download NLTK data
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newsdb
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6

databases:
  - name: newsdb
    databaseName: newsdb
    user: newsuser
